import {businessProjects} from './business-projects';
export const projects=businessProjects;
export const services=[
 {id:'web',number:'01',icon:'web',title:['Web design & development','تصميم وتطوير المواقع'],short:['Your business, beautifully translated into a digital experience.','أعمالك في تجربة رقمية تعبّر عنها.'],description:['Distinctive websites that combine thoughtful design with clear structure. From a focused landing page to a complete business website, we shape the experience around what your visitors need to do.','مواقع مميّزة تجمع التصميم المدروس بالهيكلة الواضحة. من صفحة هبوط مركّزة إلى موقع أعمال متكامل، نصمّم التجربة حول ما يحتاج زائرك إلى فعله.'],items:[['Responsive interface design','واجهات متجاوبة'],['React development','تطوير باستخدام React'],['Arabic & English experiences','تجارب بالعربية والإنجليزية'],['Basic search and accessibility setup','إعدادات أساسية للبحث وإمكانية الوصول']]},
 {id:'commerce',number:'02',icon:'shop',title:['E-commerce experiences','تجارب التجارة الإلكترونية'],short:['Help visitors discover, understand, and choose your products.','ساعد زائرك على اكتشاف منتجاتك وفهمها واختيارها.'],description:['Considered storefronts with clear collections and informative product pages. We agree on the platform, payment requirements, and catalogue scope before implementation.','متاجر مدروسة بمجموعات واضحة وصفحات منتجات مفيدة. نتفق على المنصّة ومتطلّبات الدفع ونطاق الكتالوج قبل التنفيذ.'],items:[['Collection & product design','تصميم المجموعات والمنتجات'],['Mobile shopping journeys','رحلات تسوّق للجوال'],['Platform setup within agreed scope','إعداد المنصّة ضمن النطاق المتفق عليه'],['Checkout experience planning','تخطيط تجربة إتمام الطلب']]},
 {id:'identity',number:'03',icon:'brand',title:['Brand & digital identity','الهوية البصرية والرقمية'],short:['A visual language that makes your business recognisable.','لغة بصرية تجعل أعمالك قابلة للتميّز.'],description:['An identity that carries consistently from your logo to your website. We define the colours, typography, and visual direction before applying them across your digital presence.','هوية متناسقة من الشعار إلى الموقع. نحدّد الألوان والخطوط والاتجاه البصري ثم نطبّقها عبر حضورك الرقمي.'],items:[['Logo direction','اتجاه الشعار'],['Colour & typography systems','أنظمة الألوان والخطوط'],['Website art direction','التوجيه الفني للموقع'],['Practical brand guidelines','إرشادات عملية للهوية']]},
 {id:'care',number:'04',icon:'care',title:['Website care & evolution','عناية وتطوير مستمر'],short:['A useful partnership after your website goes live.','شراكة مفيدة بعد إطلاق موقعك.'],description:['Keep your website useful as your business develops. We agree on a support plan for updates, small improvements, and platform-appropriate maintenance.','حافظ على فائدة موقعك مع تطوّر أعمالك. نتفق على خطة دعم للتحديثات والتحسينات الصغيرة والصيانة المناسبة للمنصّة.'],items:[['Content updates','تحديث المحتوى'],['Performance reviews','مراجعة الأداء'],['Platform maintenance','صيانة المنصّة'],['Clearly scoped ongoing support','دعم مستمر بنطاق واضح']]}
];

services.push(
{id:'apps',number:'05',icon:'web',title:['Mobile app development','تطوير تطبيقات الجوال'],short:['An app built around your customers.','تطبيق مصمّم حول احتياجات عملائك.'],description:['When your business needs a mobile experience, we define the screens, features, platform, and launch requirements with you before development.','حين يحتاج نشاطك إلى تجربة على الجوال، نحدّد معك الشاشات والوظائف والمنصّة ومتطلّبات الإطلاق قبل التطوير.'],items:[['App planning & interface design','تخطيط التطبيق وتصميم الواجهات'],['Platform and feature scoping','تحديد المنصّة والوظائف'],['Development & testing','التطوير والاختبار'],['Release planning','تخطيط الإطلاق']]},
{id:'software',number:'06',icon:'web',title:['Custom business software','برامج مخصّصة للأعمال'],short:['Software that fits the way you work.','برنامج يناسب طريقة عملك.'],description:['Customer portals, internal dashboards, booking tools, and tailored workflows. We start with your process and define a practical first version.','بوابات عملاء ولوحات إدارة وأدوات حجز ومسارات عمل مخصّصة. نبدأ بفهم إجراءاتك ونحدّد نسخة أولى عملية.'],items:[['Workflow discovery','فهم سير العمل'],['Custom interface design','تصميم واجهات مخصّصة'],['Agreed integrations','ربط الأنظمة المتفق عليها'],['Testing & handover','الاختبار والتسليم']]});
