import React from 'react';
import {createRoot,hydrateRoot} from 'react-dom/client';
import App from './WaslivoV2.jsx';
import './v2.css';
import './v2-pages.css';
import './v2-contact-mobile.css';
import './v3-visuals.css';
import './project-previews.css';
import './site-motion.css';
import './footer-social.css';
import './home-hero-premium.css';
import './process-section.css';
import './home-trust.css';
import './english-site.css';
const root=document.getElementById('root');
const app=<React.StrictMode><App/></React.StrictMode>;
if(root.hasChildNodes())hydrateRoot(root,app);
else createRoot(root).render(app);
