// Market pages discuss remote services for each audience; no local office is implied.
export const marketCodes = ['sa', 'ae', 'kw', 'qa', 'ma']

export const markets = {
  sa: {
    country: 'Saudi Arabia', countryAr: 'السعودية', region: 'SA',
    ar: {
      title: 'تصميم مواقع إلكترونية للأعمال في السعودية | وصليفو',
      description: 'تصميم وتطوير مواقع للشركات والمتاجر في السعودية، بهوية عربية واضحة وتجربة جوال سهلة. استكشف نماذج وصليفو وناقش احتياجات مشروعك.',
      h1: 'تصميم مواقع إلكترونية للأعمال في السعودية',
      intro: 'إذا كان جمهورك في السعودية، يحتاج موقعك إلى عرض خدماتك بسرعة ووضوح على الجوال، وإلى مسار سهل للاستفسار أو الطلب. نصمم في وصليفو تجربة عربية تراعي طبيعة نشاطك وتمنح الزائر المعلومات التي يحتاجها قبل التواصل.',
      focusTitle: 'موقع يساعد العميل على اتخاذ الخطوة التالية',
      focus: 'لشركة خدمات، نرتب الخدمات ومناطق التغطية وطريقة طلب عرض السعر. وللمتجر، نبدأ بالفئات وصفحات المنتجات وخطوات الشراء، مع تحديد متطلبات الدفع والتوصيل قبل التطوير. أما الموقع العقاري فيحتاج إلى تصنيف واضح للعقارات وتفاصيل تسهّل طلب المعاينة.',
      approachTitle: 'ما الذي نراجعه قبل التصميم؟',
      approach: 'نراجع جمهور المشروع، المحتوى العربي، الصفحات المهمة، ونقاط التواصل. نختبر القراءة والتصفح من الهاتف، ونحدد معك إن كان واتساب أو النموذج أو الحجز هو الإجراء الأنسب. لا نضيف خصائص لا تخدم هدف الموقع.',
      faq: [
        ['هل يمكن تصميم موقع لشركة تستهدف مدناً سعودية متعددة؟', 'نعم. ننظم الخدمات ومناطق التغطية الحقيقية في صفحات مفيدة للزائر، دون إنشاء صفحات مدن متكررة أو الادعاء بوجود فروع غير موجودة.'],
        ['هل يمكن ربط المتجر بخيارات دفع وتوصيل في السعودية؟', 'يمكن التخطيط لهذه التكاملات بعد اختيار منصة المتجر ومزوّدي الخدمة المناسبين؛ نحدد النطاق التقني معك قبل التنفيذ.'],
      ],
      projects: ['property', 'facilities-services', 'ecommerce'],
    },
    en: {
      title: 'Website Design for Businesses in Saudi Arabia | WASLIVO',
      description: 'WASLIVO designs Arabic-first websites and stores for businesses serving Saudi customers. Explore practical concepts and discuss your project needs.',
      h1: 'Website design for businesses in Saudi Arabia',
      intro: 'A website serving Saudi customers should make services and next steps clear on mobile. We plan Arabic-first pages around your actual business, whether visitors need a quote, a product, or a property viewing.',
      focusTitle: 'Make the next action easy',
      focus: 'A service company may need clear service areas and quote requests. A store needs useful categories, product information, and a checkout plan. A property platform benefits from organized listings and viewing enquiries.',
      approachTitle: 'What we define together',
      approach: 'We review the audience, content, key pages, and contact path before designing. Payment and delivery integrations are scoped with the chosen providers rather than assumed.',
      faq: [
        ['Can one website serve several Saudi cities?', 'Yes. We can organize genuine service areas and useful local information without repeating thin city pages or implying offices you do not have.'],
        ['Can an online store use Saudi payment and delivery providers?', 'We can plan integrations after choosing the platform and providers; availability and scope are confirmed for your project.'],
      ],
      projects: ['property', 'facilities-services', 'ecommerce'],
    },
  },
  ae: {
    country: 'United Arab Emirates', countryAr: 'الإمارات', region: 'AE',
    ar: {
      title: 'تصميم مواقع للشركات والمتاجر في الإمارات | وصليفو',
      description: 'مواقع عربية وإنجليزية واضحة للشركات والمتاجر التي تخاطب جمهور الإمارات. تعرّف على نهج وصليفو في التصميم وابدأ من احتياجات عملك.',
      h1: 'تصميم مواقع للشركات والمتاجر في الإمارات',
      intro: 'تخاطب أعمال كثيرة في الإمارات جمهوراً يستخدم العربية والإنجليزية، وغالباً ما يتعرف على العلامة من الهاتف أولاً. نرتب المحتوى واللغة ومسارات التواصل بحيث يجد كل زائر الخدمة أو المنتج المناسب دون ارتباك.',
      focusTitle: 'تجربة ثنائية اللغة عند الحاجة',
      focus: 'لا يكفي نقل النص بين لغتين حرفياً. نخطط بنية الصفحات، واتجاه القراءة، ووضوح الأزرار لكل نسخة. للشركات، نبرز نطاق الخدمات والأعمال؛ وللمتاجر، نوضح الفئات والمعلومات التي يحتاجها المشتري قبل الطلب.',
      approachTitle: 'هوية موحدة ومسار تواصل واضح',
      approach: 'نبدأ بتحديد الجمهور الذي تريد الوصول إليه، واللغة التي يحتاجها فعلاً، ثم نبني صفحات تشرح القيمة وتدعو إلى التواصل. يمكن ربط الموقع بواتساب أو نموذج، مع مراعاة أداء الصور على شبكات الجوال.',
      faq: [
        ['هل يمكن إنشاء موقع عربي وإنجليزي للشركة؟', 'نعم. نصمم النسختين ببنية متناسقة وروابط لغة واضحة، مع مراجعة النصوص واتجاه الواجهة لكل لغة.'],
        ['هل يمكن عرض خدمات الشركة ومشاريعها في الموقع؟', 'نعم. نرتب صفحات الخدمات ونماذج الأعمال التي تملك حق نشرها، ونضع دعوة واضحة للاستفسار أو طلب عرض.'],
      ],
      projects: ['facilities-services', 'resort-hotel', 'beauty-store'],
    },
    en: {
      title: 'Website Design for UAE Businesses & Stores | WASLIVO',
      description: 'Clear Arabic and English websites for businesses serving the UAE. See WASLIVO concepts and discuss a website built around your audience.',
      h1: 'Website design for businesses serving the UAE',
      intro: 'Many UAE businesses speak to both Arabic and English audiences. We plan each language around the same business goals while keeping navigation, reading direction, and calls to action clear on mobile.',
      focusTitle: 'Bilingual content that makes sense',
      focus: 'A useful bilingual website needs more than literal translation. We define the pages, service explanations, portfolio evidence you can publish, and product details visitors need before contacting you.',
      approachTitle: 'A consistent identity across languages',
      approach: 'We review your audience and actual language needs, then design a consistent interface with clear contact options. Image performance and mobile usability are part of the scope.',
      faq: [
        ['Can you design both Arabic and English versions?', 'Yes. We plan corresponding pages, language links, and reading direction, then review content for each audience.'],
        ['Can the website present our services and projects?', 'Yes. We can structure service pages and examples you have permission to publish, with a clear enquiry route.'],
      ],
      projects: ['facilities-services', 'resort-hotel', 'beauty-store'],
    },
  },
  kw: {
    country: 'Kuwait', countryAr: 'الكويت', region: 'KW',
    ar: {
      title: 'تصميم مواقع إلكترونية للشركات في الكويت | وصليفو',
      description: 'وصليفو تصمم مواقع للشركات والمتاجر التي تخدم عملاء الكويت، بمحتوى عربي واضح وصفحات متجاوبة. شاهد النماذج وناقش مشروعك.',
      h1: 'تصميم مواقع إلكترونية للشركات في الكويت',
      intro: 'الموقع الجيد لعملاء الكويت يختصر الطريق من السؤال إلى الإجابة: ما الخدمة، أين تتوفر، وكيف أطلبها؟ نرتب هذه المعلومات في صفحات عربية سهلة القراءة على الهاتف، ونساعدك على اختيار وسيلة تواصل تناسب طريقة عمل فريقك.',
      focusTitle: 'المعلومة المهمة أولاً',
      focus: 'في موقع شركة خدمات، يحتاج الزائر إلى فهم التخصصات وآلية الطلب. وفي موقع مطعم، يبحث عن القائمة والحجز أو الاستفسار. أما المتجر فيحتاج إلى صور منتجات واضحة ومعلومات تسليم وسياسات تشرحها أنت بدقة.',
      approachTitle: 'تصميم يناسب التشغيل اليومي',
      approach: 'نخطط لتحديث المحتوى بعد الإطلاق: من سيعدل الخدمات أو القائمة أو المنتجات؟ وبناءً على ذلك نختار بنية عملية وواجهة تحافظ على سرعة التصفح. كل تكامل أو وظيفة إضافية يحدد نطاقها قبل التنفيذ.',
      faq: [
        ['هل يمكن إضافة قائمة خدمات أو مطعم قابلة للتحديث؟', 'نعم. نحدد طريقة إدارة المحتوى بحسب عدد العناصر ومن سيتولى التحديث، ثم نبني الواجهة المناسبة.'],
        ['هل تقدمون تواصلاً مباشراً من الموقع؟', 'يمكن إضافة واتساب أو نموذج استفسار أو طلب حجز، حسب الإجراءات التي يستخدمها مشروعك فعلاً.'],
      ],
      projects: ['restaurant', 'automotive', 'ecommerce'],
    },
    en: {
      title: 'Website Design for Kuwait Businesses | WASLIVO',
      description: 'Clear, mobile-ready websites for companies and stores serving customers in Kuwait. Explore concepts and discuss the right website structure.',
      h1: 'Website design for businesses serving Kuwait',
      intro: 'Visitors want quick answers: what you offer, where it is available, and how to request it. We make that path easy to follow on mobile and plan Arabic content around the way your team handles enquiries.',
      focusTitle: 'Put useful information first',
      focus: 'A service company needs clear specialties. A restaurant needs an accessible menu and booking path. A store needs product images, delivery information, and policies supplied by the business.',
      approachTitle: 'Designed for everyday updates',
      approach: 'We ask who will maintain services, menus, or products after launch. That informs the site structure and any content-management features, which are agreed before development.',
      faq: [
        ['Can our team update services or menu items?', 'Yes. We can plan a suitable content workflow based on the number of items and your team’s needs.'],
        ['Can visitors contact us directly?', 'We can add WhatsApp, an enquiry form, or a booking request according to your real process.'],
      ],
      projects: ['restaurant', 'automotive', 'ecommerce'],
    },
  },
  qa: {
    country: 'Qatar', countryAr: 'قطر', region: 'QA',
    ar: {
      title: 'تصميم وتطوير مواقع إلكترونية في قطر | وصليفو',
      description: 'مواقع واضحة ومتجاوبة للأعمال التي تخاطب جمهور قطر، من التعريف بالخدمات إلى الاستفسار والحجز. اطلع على نماذج وصليفو.',
      h1: 'تصميم وتطوير مواقع للأعمال في قطر',
      intro: 'حين يبحث الزائر في قطر عن خدمة أو عيادة أو إقامة، يريد معرفة ما تقدمه الجهة وكيف يتواصل معها بثقة. ننظم الصفحات حول هذه الأسئلة، ونوازن بين الصور والمعلومات العملية حتى لا تتحول الواجهة إلى عرض بصري يصعب استخدامه.',
      focusTitle: 'تفاصيل تساعد على الاختيار',
      focus: 'يمكن لموقع عيادة أن يشرح الخدمات والفريق وطريقة طلب موعد دون وعود طبية مبالغ فيها. ويمكن لموقع ضيافة أن يعرض الغرف والمرافق وشروط الاستفسار بوضوح. وللشركة، نبرز الخبرات والخدمات التي تستطيع إثباتها.',
      approachTitle: 'من أول زيارة إلى طلب الاستفسار',
      approach: 'نصمم التنقل والمحتوى على الجوال، ونتفق على المعلومات المطلوبة في نموذج التواصل أو الحجز. لا ننشر شهادات أو تقييمات أو أرقاماً لم يقدمها المشروع ويتحقق منها.',
      faq: [
        ['هل يمكن تصميم موقع عيادة مع طلب مواعيد؟', 'نعم. نرتب معلومات الخدمات والفريق وطريقة الطلب، ثم نحدد إن كان المطلوب نموذج طلب أو نظام حجز وفق سير العمل الفعلي.'],
        ['هل يمكن إضافة نسخة إنجليزية؟', 'نعم، إذا كان جمهورك يحتاجها. نخطط للنسختين مع روابط لغة واضحة ومحتوى مناسب لكل نسخة.'],
      ],
      projects: ['dental', 'resort-hotel', 'facilities-services'],
    },
    en: {
      title: 'Website Design & Development for Qatar | WASLIVO',
      description: 'Mobile-ready websites for businesses serving Qatar, with clear service, booking, and enquiry paths. Explore WASLIVO concepts.',
      h1: 'Website design for businesses serving Qatar',
      intro: 'People comparing a clinic, hospitality venue, or service provider need credible details and an easy way to enquire. We balance imagery with practical information so the website remains useful on a phone.',
      focusTitle: 'Details that help visitors decide',
      focus: 'A clinic can explain services, its real team, and appointment requests without exaggerated medical promises. A hospitality site can present rooms and facilities. A company can explain work it can substantiate.',
      approachTitle: 'From first visit to enquiry',
      approach: 'We plan mobile navigation and agree on the information a form or booking request should collect. Testimonials and performance figures are used only when the business can verify them.',
      faq: [
        ['Can a clinic website accept appointment requests?', 'Yes. We define whether you need a simple request form or a booking integration based on your actual workflow.'],
        ['Can we add an Arabic version?', 'Yes, when your audience needs it. We plan the corresponding content, reading direction, and language links.'],
      ],
      projects: ['dental', 'resort-hotel', 'facilities-services'],
    },
  },
  ma: {
    country: 'Morocco', countryAr: 'المغرب', region: 'MA',
    ar: {
      title: 'إنشاء مواقع إلكترونية للأعمال في المغرب | وصليفو',
      description: 'تصميم وتطوير مواقع للشركات والمتاجر في المغرب، بمحتوى منظم وتجربة جوال واضحة. شاهد نماذج وصليفو وابدأ نقاش مشروعك.',
      h1: 'إنشاء مواقع إلكترونية للأعمال في المغرب',
      intro: 'تحتاج المشاريع في المغرب إلى موقع يشرح نشاطها للعميل بوضوح، سواء كان يبحث عن خدمة محلية أو منتجات أو تجربة إقامة. نبدأ بالهدف والجمهور واللغة المناسبة، ثم نرتب صفحات يسهل استخدامها ومتابعة محتواها.',
      focusTitle: 'من تعريف النشاط إلى تواصل قابل للمتابعة',
      focus: 'لمشروع التصميم الداخلي، قد يكون معرض الأعمال وطريقة طلب الاستشارة أهم من كثرة الصفحات. وللمتجر، نحدد فئات المنتجات وخطوات الطلب. وفي الضيافة، نوضح المرافق ومعلومات الإقامة ومسار الاستفسار قبل التفكير في وظائف حجز معقدة.',
      approachTitle: 'لغة ومحتوى يناسبان جمهورك',
      approach: 'يمكن تخطيط نسخة عربية وإنجليزية عندما تحتاجها فعلاً، مع إمكانية دراسة الفرنسية لاحقاً بعد تجهيز محتوى أصلي لها. نتفق على وسيلة التواصل، الصور التي تملكها، وطريقة تحديث المعلومات بعد الإطلاق.',
      faq: [
        ['هل يمكن البدء بموقع تعريفي ثم إضافة متجر؟', 'نعم. يمكن وضع بنية تقبل التوسع، لكن نحدد ما يدخل في المرحلة الأولى وما يحتاج إلى تطوير لاحق.'],
        ['هل يجب أن يكون الموقع بلغات متعددة؟', 'يعتمد على جمهورك ومحتواك المتاح. نفضل نسخة قوية بلغة واحدة على نسخ مترجمة آلياً بلا مراجعة.'],
      ],
      projects: ['interior-design', 'resort-hotel', 'beauty-store'],
    },
    en: {
      title: 'Website Creation for Businesses in Morocco | WASLIVO',
      description: 'WASLIVO designs clear, mobile-ready websites for Moroccan businesses and stores. See relevant concepts and discuss your project.',
      h1: 'Website creation for businesses serving Morocco',
      intro: 'A useful website explains what a business offers and how to take the next step, whether the visitor is comparing local services, products, or accommodation. We start with audience, language, and the content your team can maintain.',
      focusTitle: 'Show the work, then make contact easy',
      focus: 'An interior design studio may need a strong portfolio and consultation path. A store needs clear categories and order steps. Hospitality sites need facilities and stay information before advanced booking features.',
      approachTitle: 'Choose languages deliberately',
      approach: 'Arabic and English versions can be planned when there is real demand and reviewed content. French can be considered later with original copy; we do not publish automatic translations just to create more pages.',
      faq: [
        ['Can we start with a company site and add a store later?', 'Yes. We can plan for expansion while agreeing which features belong in the first phase.'],
        ['Does the site need several languages?', 'That depends on your audience and available content. One strong version is better than several unreviewed translations.'],
      ],
      projects: ['interior-design', 'resort-hotel', 'beauty-store'],
    },
  },
}
