import React from 'react';
import {ArrowLeft,ArrowRight,Check,Layers,Monitor,PenTool} from 'lucide-react';
import './portfolio.css';

// Miniature website compositions are decorative previews; the outer link opens the case study.
function WebsiteThumbnail({p}){
 const image=p.image||'interior.png';
 const labels={forme:['Selected spaces','Private residence','A considered interior','Explore our approach'],ritual:['Find your daily ritual','House blend','Slow mornings','From origin to your cup'],aura:['Care, made simple','Daily essentials','A moment for yourself','Thoughtfully formulated'],object:['The collection','Everyday objects','Materials that matter','Made for living'],build:['Our expertise','Interior renovation','Spaces built around you','A clear path from plan to finish']}[p.id]||[];
 if(p.id==='orbit')return <div className="thumb-dashboard"><aside><b>orbit ✳</b><span>Overview</span><span>My projects</span><span>Tasks</span><span>Calendar</span><span>Settings</span></aside><div className="thumb-dashboard-main"><div className="thumb-dashboard-top">Your workspace <span>Search projects…　 ⌕</span></div><h4>Make room for your best work.</h4><p>Your projects, priorities, and next steps. Together.</p><div className="thumb-stats">{[['04','Active projects'],['08','Tasks this week'],['12','Completed tasks']].map(([v,l])=><div key={l}><small>{l}</small><b>{v}</b><span>Project overview</span></div>)}</div><div className="thumb-board">{['Planning','In progress','Review'].map((s,i)=><div key={s}><strong>{s} <span>02</span></strong>{['Website direction','Content & design'].map((n,j)=><article key={n}><i style={{background:['#d9d0fd','#c3e3d2','#f6d7b9'][i]}}/><b>{n}</b><p>{['Brand experience','Homepage layout','Design system'][i]}</p><footer><span>◉ ◉</span><span>0{j+1} / 06</span></footer></article>)}</div>)}</div><div className="thumb-dash-bottom"><b>Upcoming milestones</b><span>Website review</span><span>Content handover</span><span>Launch preparation</span></div></div></div>;
 return <div className={`website-thumbnail thumbnail-${p.id}`} style={{'--thumb-bg':p.color,'--thumb-ink':p.ink}}><div className="thumb-nav"><b>{p.name}<sup>✳</sup></b><span>Home　 About　 {p.category==='E-commerce'?'Shop':'Projects'}　 Contact</span><em>{p.category==='E-commerce'?'Shop collection':'Get in touch'} ↗</em></div><div className="thumb-hero"><img src={`./assets/${image}`} alt="" loading="lazy"/><div><small>{p.tag[0]}</small><h4>{p.title[0]}</h4><p>{p.short[0]}</p><span>{p.category==='E-commerce'?'Explore the collection':'Discover our work'}　→</span></div></div><div className="thumb-section-heading"><b>{labels[0]}</b><span>View all　→</span></div><div className="thumb-products">{[0,1,2].map((n)=><div key={n}><img src={`./assets/${image}`} alt="" loading="lazy" style={{objectPosition:['20% 50%','80% 65%','50% 90%'][n]}}/><b>{[labels[1],p.id==='ritual'?'Single origin':p.id==='aura'?'The care collection':'Signature collection',p.id==='ritual'?'Brewing essentials':'New perspectives'][n]}</b><span>{p.category==='E-commerce'?'Discover more':'View project'}　↗</span></div>)}</div><div className="thumb-story"><div><small>OUR APPROACH</small><h4>{labels[2]}</h4><p>{labels[3]}. Design, detail, and a considered experience.</p><span>Our story　→</span></div><img src={`./assets/${image}`} alt="" loading="lazy"/></div><div className="thumb-features">{[[PenTool,'Considered design'],[Layers,'Quality in every detail'],[Monitor,'A seamless experience']].map(([Icon,l])=><span key={l}><Icon/>{l}</span>)}</div><div className="thumb-footer"><b>{p.name}</b><span>About　 Collection　 Contact</span><small>A WASLIVO DESIGN CONCEPT</small></div></div>
}
export default function PortfolioCard({project:p,t,pair}){return <a href={`#/work/${p.id}`} className={`portfolio-reference-card portfolio-${p.id}`} aria-label={`${t('View project','عرض المشروع')}: ${p.name}`}><div className="portfolio-browser" aria-hidden="true"><div className="portfolio-browser-bar"><i/><i/><i/></div><div className="portfolio-browser-page"><WebsiteThumbnail p={p}/></div></div><div className="portfolio-card-copy"><span className="portfolio-industry">{pair(p.tag)}</span><h3>{t(`${p.name} — website concept`,`${p.arabic} — تصوّر موقع`)}</h3><p>{pair(p.short)} {t('An original design exploration of layout, content, and user experience.','تصوّر أصلي يستكشف التصميم والمحتوى وتجربة المستخدم.')}</p><span className="portfolio-card-action">{t('View project','عرض المشروع')}{t(<ArrowRight size={17}/>,<ArrowLeft size={17}/>)}</span></div></a>}
