import React,{useState} from 'react';
import {ArrowLeft,ArrowUpLeft,CalendarDays,Check,ChevronDown,Heart,Mail,MapPin,Menu,Phone,Search,ShoppingBag,X} from 'lucide-react';
import './project-demos.css';

const img=name=>`/assets/${name}`;
const demos={
  dental:{brand:'صفاء',label:'عيادة أسنان',theme:'dental',image:'dental.webp',eyebrow:'رعاية تبدأ بابتسامة',title:'ابتسامتك في أيدٍ تهتم بالتفاصيل',intro:'خدمات أسنان واضحة وتجربة مريحة من أول سؤال إلى موعدك القادم.',cta:'اطلب موعداً',categories:['الكل','العناية الوقائية','تجميل الأسنان','العلاج'],cards:[['فحص شامل','العناية الوقائية','نبدأ بفهم احتياجاتك وخطة عناية مناسبة.','dental.webp'],['تنظيف الأسنان','العناية الوقائية','عناية دورية تمنحك إحساساً بالانتعاش.','dental.webp'],['تبييض الأسنان','تجميل الأسنان','خيارات مدروسة لابتسامة مشرقة وطبيعية.','dental.webp'],['ترميم الأسنان','العلاج','حلول تهتم بالراحة والنتيجة طويلة المدى.','dental.webp']],section:'خدمات مصممة لراحتك',story:'موعدك، بكل وضوح',storyText:'تعرّف على الخدمات والخطوات الأساسية قبل الزيارة، ثم أرسل طلب موعد يناسب وقتك.',form:'طلب موعد'},
  restaurant:{brand:'مذاق الشرق',label:'مطعم',theme:'restaurant',image:'restaurant.webp',eyebrow:'تجربة طعام تُحكى',title:'نكهات تُصنع بشغف وتُقدّم بذوق',intro:'قائمة مختارة من الأطباق الطازجة، وجلسات تجمع من تحب حول طاولة واحدة.',cta:'احجز طاولتك',categories:['الكل','الأطباق الرئيسية','المقبلات','الحلويات'],cards:[['طبق الشيف','الأطباق الرئيسية','طبق غني بالنكهات يقدم بعناية.','restaurant.webp'],['مشاوي مختارة','الأطباق الرئيسية','اختيار مثالي لمحبي النكهة الأصيلة.','restaurant.webp'],['مقبلات الموسم','المقبلات','بداية خفيفة تفتح شهيتك للوجبة.','coffee.webp'],['حلوى الدار','الحلويات','ختام دافئ لتجربة تستحق التذكر.','coffee.webp']],section:'من قائمتنا',story:'مساحة للقاءات الجميلة',storyText:'أجواء هادئة وتفاصيل مدروسة تجعل كل زيارة مناسبة خاصة.',form:'طلب حجز'},
  property:{brand:'سُكون',label:'منصة عقارية',theme:'property',image:'interior.webp',eyebrow:'مساحتك القادمة تبدأ هنا',title:'ابحث عن منزل يشبه طموحك',intro:'اكتشف مساحات مختارة، وقارن التفاصيل، وابدأ رحلة العثور على المكان المناسب.',cta:'استكشف العقارات',categories:['الكل','شقق','فلل','مكاتب'],cards:[['شقة بإطلالة مفتوحة','شقق','مساحات رحبة وإضاءة طبيعية طوال اليوم.','interior.webp'],['فيلا معاصرة','فلل','خصوصية وراحة في تصميم مدروس.','hero-property-v2.webp'],['مكتب عصري','مكاتب','بيئة عمل مرنة تعكس أسلوب فريقك.','studio-workspace.webp'],['شقة عائلية','شقق','توزيع ذكي ومساحات مناسبة للحياة اليومية.','interior.webp']],section:'عقارات مختارة',story:'التفاصيل التي تهمك، في مكان واحد',storyText:'استعرض نوع العقار ومميزاته بوضوح، ثم اطلب معلومات إضافية عندما تجد ما يناسبك.',form:'طلب معلومات'},
  legal:{brand:'ميزان',label:'مكتب استشارات',theme:'legal',image:'legal.webp',eyebrow:'رؤية واضحة لكل قرار',title:'استشارة مهنية تبدأ بالإنصات',intro:'نقدّم شرحاً منظماً لمجالات العمل وطريقة بدء الاستفسار بثقة ووضوح.',cta:'أرسل استفسارك',categories:['الكل','الشركات','العقود','الاستشارات'],cards:[['استشارات الأعمال','الشركات','فهم احتياجات النشاط وخياراته القانونية.','legal.webp'],['مراجعة العقود','العقود','مراجعة دقيقة للبنود والالتزامات.','legal.webp'],['استشارة أولية','الاستشارات','خطوة أولى لتحديد المسار المناسب.','legal.webp']],section:'مجالات عملنا',story:'وضوح في الخطوات، واهتمام بالتفاصيل',storyText:'اختر مجال الاستفسار وشارك ملخصاً مناسباً؛ وسيكون التواصل الأول فرصة لفهم احتياجك.',form:'طلب استشارة'},
  beauty:{brand:'لُمسة',label:'استوديو عناية',theme:'beauty',image:'skincare.webp',eyebrow:'وقت تخصصينه لنفسك',title:'عناية تمنح يومك لمسة مختلفة',intro:'جلسات هادئة وخيارات عناية مصممة لتناسب إيقاعك وشخصيتك.',cta:'احجزي موعداً',categories:['الكل','البشرة','الشعر','التجارب'],cards:[['جلسة إشراقة','البشرة','طقس عناية يمنح بشرتك انتعاشاً لطيفاً.','skincare.webp'],['عناية الشعر','الشعر','تفاصيل صغيرة تصنع فرقاً كبيراً.','skincare.webp'],['تجربة استرخاء','التجارب','مساحة هادئة للاهتمام بنفسك.','coffee.webp']],section:'تجارب العناية',story:'جمال يبدأ بالاهتمام',storyText:'اكتشفي الخدمات وأرسلي طلب موعدك بخطوات قصيرة وواضحة.',form:'طلب موعد'},
  automotive:{brand:'عزم',label:'خدمات سيارات',theme:'automotive',image:'automotive.webp',eyebrow:'العناية التي تستحقها سيارتك',title:'خدمة واضحة. أداء تطمئن إليه.',intro:'استكشف الخدمات واختر ما تحتاجه سيارتك، من الفحص الدوري إلى العناية التفصيلية.',cta:'اطلب فحصاً',categories:['الكل','الفحص','الصيانة','العناية'],cards:[['فحص شامل','الفحص','نراجع حالة السيارة ونوضح الخطوة التالية.','automotive.webp'],['صيانة دورية','الصيانة','متابعة منتظمة لأداء أكثر ثباتاً.','automotive.webp'],['عناية تفصيلية','العناية','اهتمام بالمظهر والتفاصيل التي تلاحظها.','automotive.webp']],section:'خدماتنا',story:'نعرف أن وقتك مهم',storyText:'صف احتياجك في طلب قصير، ثم ناقش تفاصيل الخدمة قبل موعد الزيارة.',form:'طلب فحص'},
  plumbing:{brand:'سند',label:'خدمات منزلية',theme:'plumbing',image:'plumbing.webp',eyebrow:'حلول لراحة منزلك',title:'خدمة منزلية تصل إلى أصل المشكلة',intro:'تعرّف على التخصصات، أرسل تفاصيل طلبك، واحصل على خطوة تالية واضحة.',cta:'اطلب خدمة',categories:['الكل','السباكة','الصيانة','التركيب'],cards:[['إصلاح التسربات','السباكة','تحديد مصدر المشكلة قبل بدء الإصلاح.','plumbing.webp'],['صيانة منزلية','الصيانة','حلول عملية للمشكلات اليومية.','plumbing.webp'],['تركيب وتجديد','التركيب','تنفيذ مرتب يناسب احتياج المساحة.','plumbing.webp']],section:'ما الذي يمكننا مساعدتك فيه؟',story:'ابدأ بطلب بسيط',storyText:'اختر نوع الخدمة واكتب وصفاً مختصراً لنتمكن من فهم احتياجك.',form:'طلب خدمة'},
  ecommerce:{brand:'نَقاء',label:'متجر إلكتروني',theme:'ecommerce',image:'skincare.webp',eyebrow:'اختيارات تعتني بك',title:'منتجات مختارة لروتين أجمل',intro:'تصفح المجموعة، قارن الخيارات، وأضف ما يعجبك إلى سلتك التجريبية.',cta:'تسوق المجموعة',categories:['الكل','العناية بالبشرة','العناية اليومية','هدايا'],cards:[['مجموعة الإشراقة','العناية بالبشرة','خطوات بسيطة لبشرة تستحق الاهتمام.','skincare.webp'],['عناية يومية','العناية اليومية','أساسيات لطيفة لروتينك اليومي.','skincare.webp'],['هدية العناية','هدايا','اختيار أنيق لتقدمه لمن تحب.','skincare.webp']],section:'اكتشف المجموعة',story:'تجربة تسوق هادئة وواضحة',storyText:'فئات منظمة وتفاصيل تساعدك على اختيار المنتج المناسب بسهولة.',form:'استفسر عن منتج'},
  education:{brand:'أُفق',label:'منصة تعليمية',theme:'education',image:'education-v2.webp',eyebrow:'تعلّم بخطوات واثقة',title:'مسارات تعليمية تناسب أهدافك',intro:'استكشف البرامج، اطّلع على محاورها، وحدد الخطوة التي تساعدك على التقدم.',cta:'استكشف البرامج',categories:['الكل','التصميم','الأعمال','التقنية'],cards:[['أساسيات التصميم','التصميم','مدخل عملي إلى التفكير والتصميم البصري.','education-v2.webp'],['مهارات الأعمال','الأعمال','أدوات تساعدك على تنظيم قراراتك.','studio-workspace.webp'],['بناء المواقع','التقنية','تعرّف على أساسيات بناء تجربة رقمية.','education-v2.webp']],section:'برامج للخطوة التالية',story:'التعلّم يبدأ باختيار واضح',storyText:'تفاصيل البرامج منظمة لتساعدك على مقارنة المحتوى والتواصل قبل التسجيل.',form:'استفسار عن برنامج'},
  company:{brand:'بُنيان',label:'شركة خدمات',theme:'company',image:'studio-workspace.webp',eyebrow:'شريك يفهم تفاصيل العمل',title:'خدمات مهنية تدفع مشروعك إلى الأمام',intro:'نقدّم حلولاً واضحة ومسار تعاون منظم يبدأ بفهم احتياجك.',cta:'استعرض الخدمات',categories:['الكل','الاستراتيجية','التنفيذ','المتابعة'],cards:[['تحليل الاحتياجات','الاستراتيجية','نحدد الأولويات قبل اختيار الحلول.','studio-workspace.webp'],['تنفيذ المشاريع','التنفيذ','خطوات عملية ومخرجات قابلة للمراجعة.','studio-workspace.webp'],['متابعة مستمرة','المتابعة','نراجع التقدم ونوضح الخطوة القادمة.','studio-workspace.webp']],section:'كيف نساعد أعمالك؟',story:'وضوح من اللقاء الأول',storyText:'تعرف على مجالات الخدمة وطريقة العمل قبل أن ترسل تفاصيل مشروعك.',form:'طلب استفسار'}
};

export function DemoSite({id}){
 const d=demos[id]; const [filter,setFilter]=useState('الكل'); const [menuOpen,setMenuOpen]=useState(false); const [selected,setSelected]=useState([]); const [sent,setSent]=useState(false);
 if(!d)return <main className="demo-missing">النموذج غير موجود</main>;
 const visible=d.cards.filter(card=>filter==='الكل'||card[1]===filter);
 const go=(section)=>{document.getElementById(`demo-${section}`)?.scrollIntoView({behavior:'smooth'});setMenuOpen(false)};
 const toggle=(name)=>setSelected(current=>current.includes(name)?current.filter(x=>x!==name):[...current,name]);
 return <div className={`demo-site demo-${d.theme}`} dir="rtl" lang="ar">
   <div className="demo-disclosure">نموذج تفاعلي من وصليفو</div>
   <header className="demo-header"><div className="demo-wrap demo-header-inner"><button className="demo-brand" onClick={()=>go('top')} type="button"><span className="demo-brand-mark">{d.brand.slice(0,1)}</span><span><strong>{d.brand}</strong><small>{d.label}</small></span></button><nav className={menuOpen?'demo-nav demo-nav-open':'demo-nav'} aria-label="التنقل داخل النموذج"><button onClick={()=>go('top')}>الرئيسية</button><button onClick={()=>go('collection')}>{id==='restaurant'?'القائمة':id==='property'?'العقارات':id==='ecommerce'?'المنتجات':'الخدمات'}</button><button onClick={()=>go('story')}>من نحن</button><button onClick={()=>go('contact')}>تواصل معنا</button></nav><button className="demo-header-action" onClick={()=>go('contact')}>{d.form} <ArrowUpLeft size={15}/></button><button className="demo-menu-button" type="button" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?'إغلاق القائمة':'فتح القائمة'}>{menuOpen?<X/>:<Menu/>}</button></div></header>
   <main id="demo-top"><section className="demo-hero"><img src={img(d.image)} alt=""/><div className="demo-hero-shade"/><div className="demo-wrap demo-hero-content"><span className="demo-kicker">{d.eyebrow}</span><h1>{d.title}</h1><p>{d.intro}</p><button className="demo-primary" onClick={()=>go(id==='property'||id==='ecommerce'||id==='education'?'collection':'contact')}>{d.cta}<ArrowLeft size={18}/></button></div><div className="demo-hero-index">01 / 03 <span/></div></section>
   <section className="demo-stats"><div className="demo-wrap"><span><Check size={18}/> تجربة واضحة على كل شاشة</span><span><Heart size={18}/> اهتمام بالتفاصيل</span><span><CalendarDays size={18}/> خطوة تالية بسيطة</span></div></section>
   <section id="demo-collection" className="demo-section demo-collection"><div className="demo-wrap"><div className="demo-section-heading"><div><span className="demo-kicker">اكتشف المزيد</span><h2>{d.section}</h2></div><p>تصفّح الخيارات واختر المجال الذي يهمك.</p></div><div className="demo-filters" role="group" aria-label="تصفية القائمة">{d.categories.map(c=><button key={c} type="button" className={filter===c?'selected':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="demo-grid">{visible.map(([name,category,copy,photo])=><article className="demo-card" key={name}><div className="demo-card-image"><img src={img(photo)} alt="" loading="lazy"/><span>{category}</span></div><div className="demo-card-copy"><h3>{name}</h3><p>{copy}</p><button type="button" onClick={()=>id==='ecommerce'?toggle(name):go('contact')}>{id==='ecommerce'?(selected.includes(name)?'إزالة من السلة':'أضف إلى السلة'):'اعرف المزيد'} <ArrowLeft size={16}/></button></div></article>)}</div>{id==='ecommerce'&&<p className="demo-cart"><ShoppingBag size={18}/> السلة التجريبية: {selected.length} {selected.length===1?'منتج':'منتجات'}</p>}</div></section>
   <section id="demo-story" className="demo-story"><div className="demo-story-image"><img src={img(d.image)} alt="" loading="lazy"/></div><div className="demo-story-content"><span className="demo-kicker">عن التجربة</span><h2>{d.story}</h2><p>{d.storyText}</p><div className="demo-story-points"><span><Check size={18}/> معلومات واضحة</span><span><Check size={18}/> تصميم يناسب الجوال</span><span><Check size={18}/> تواصل بخطوات سهلة</span></div><button type="button" onClick={()=>go('contact')}>ابدأ من هنا <ArrowLeft size={17}/></button></div></section>
   <section id="demo-contact" className="demo-section demo-contact"><div className="demo-wrap demo-contact-grid"><div><span className="demo-kicker">تواصل معنا</span><h2>{d.form}</h2><p>هذا النموذج جزء من العرض التوضيحي. يمكنك تجربته؛ لن يتم إرسال بياناتك إلى أي جهة.</p><div className="demo-contact-method"><Mail size={19}/> نموذج تواصل تجريبي</div><div className="demo-contact-method"><MapPin size={19}/> تفاصيل المكان تُضاف عند تنفيذ المشروع</div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>الاسم<input required placeholder="اكتب اسمك"/></label><label>البريد الإلكتروني<input type="email" required placeholder="name@example.com" dir="ltr"/></label><label>رسالتك<textarea required rows="4" placeholder="أخبرنا بما تحتاجه"/></label><button className="demo-primary" type="submit">إرسال تجريبي <ArrowLeft size={17}/></button>{sent&&<p className="demo-success" role="status">نجحت تجربة النموذج. لم تُرسل أي بيانات.</p>}</form></div></section></main>
   <footer className="demo-footer"><div className="demo-wrap"><strong>{d.brand}</strong><span>تصوّر تفاعلي من وصليفو · {d.label}</span><button type="button" onClick={()=>go('top')}>العودة للأعلى ↑</button></div></footer>
 </div>
}
