import React,{useEffect,useLayoutEffect,useState} from 'react';
import {ArrowLeft,ArrowUpLeft,CalendarDays,Check,ChevronDown,Code2,Diamond,Facebook,Headphones,Heart,HeartHandshake,House,Instagram,Layers3,Lightbulb,Mail,MapPin,Menu,MessageCircle,Monitor,Palette,PenTool,Phone,Search,Send,ShieldCheck,ShoppingBag,Smartphone,Sparkles,Star,TrendingUp,Wallet,X,Zap} from 'lucide-react';
import {articles,faqItems,featuredProject,filters,projects,services,whatsapp,whatsappNumber} from './v2-data';
import HomeHero from './HomeHero';
import ProcessSection from './ProcessSection';
import HomeTrust from './HomeTrust';
import EnglishSite from './EnglishSite';
import LanguageSwitcher from './LanguageSwitcher';
import {getSeo,getStructuredData} from './seo-data';

const asset=name=>`/assets/${name}`;
const nav=[['/','الرئيسية'],['/services','خدماتنا'],['/portfolio','أعمالنا'],['/packages','باقاتنا'],['/about','من نحن'],['/#process','كيف نعمل'],['/#faq','الأسئلة الشائعة'],['/blog','مقالات'],['/contact','تواصل معنا']];
const icons={websites:Monitor,development:Code2,commerce:ShoppingBag,apps:Smartphone,logos:PenTool,identity:Diamond,social:Layers3};
const waText={general:'مرحباً وصليفو، أود مناقشة مشروع موقع إلكتروني.',portfolio:'مرحباً وصليفو، لدي مشروع مشابه لأحد النماذج المعروضة وأود مناقشته.',packages:'مرحباً وصليفو، أود معرفة الباقة المناسبة لمشروعي.'};

function go(to){const [path,hash]=to.split('#');window.history.pushState({},'',path+(hash?'#'+hash:''));window.dispatchEvent(new PopStateEvent('popstate'));requestAnimationFrame(()=>{if(hash)document.getElementById(hash)?.scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'instant'})})}
function Link({to='/',children,className='',onClick,...props}){return <a href={to} className={className} onClick={e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();onClick?.();go(to)}} {...props}>{children}</a>}
function WButton({children='تواصل معنا عبر واتساب',message=waText.general,kind='gold',className=''}){return <a href={whatsapp(message)} target="_blank" rel="noopener noreferrer" className={`button button-${kind} ${className}`}><MessageCircle size={18}/>{children}</a>}
function WhatsappIcon(){return <svg viewBox="0 0 32 32" aria-hidden="true" focusable="false"><path fill="currentColor" d="M16 2.5A13.5 13.5 0 0 0 4.4 22.9L2.5 29.5l6.8-1.8A13.5 13.5 0 1 0 16 2.5Zm0 24.4a10.8 10.8 0 0 1-5.5-1.5l-.4-.2-4 .9 1-3.9-.3-.4A10.8 10.8 0 1 1 16 26.9Zm6-8.1c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.4.2-.7.1-1.7-.9-2.9-1.9-3.9-3.5-.3-.4.3-.5.8-1.4.1-.2 0-.4 0-.5l-1-2.3c-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.8s1.3 3.2 1.5 3.5c.2.2 2.5 3.8 6 5.1 2.3.9 3.2 1 4.3.8.7-.1 1.8-.7 2.1-1.5.3-.8.3-1.5.2-1.6-.1-.1-.3-.2-.6-.4Z"/></svg>}
function Logo({light=false}){return <Link to="/" className={`logo ${light?'logo-light':''}`} aria-label="وصليفو - الصفحة الرئيسية"><img src={asset('waslivo-logo.webp')} alt="وصليفو | WASLIVO" width="142" height="69"/></Link>}
function Header({path}){const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);useEffect(()=>{const fn=()=>setScrolled(window.scrollY>35);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);useEffect(()=>setOpen(false),[path]);return <header className={`header ${scrolled?'header-scrolled':''}`}><div className="header-inner"><Logo/><nav className={open?'header-nav header-nav-open':'header-nav'} aria-label="التنقل الرئيسي">{nav.map(([to,label])=><Link key={to} to={to} onClick={()=>setOpen(false)} className={(path===to||to==='/#process'&&(typeof window!=='undefined'&&window.location.hash==='#process')||to==='/#faq'&&(typeof window!=='undefined'&&window.location.hash==='#faq'))?'active':''}>{label}</Link>)}<WButton className="drawer-wa"/></nav><LanguageSwitcher path={path}/><WButton className="header-wa">تواصل معنا عبر واتساب</WButton><button className="nav-toggle" type="button" aria-expanded={open} aria-label={open?'إغلاق القائمة':'فتح القائمة'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function TiktokIcon(){return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="M12.53.02C13.84 0 15.14.01 16.44 0c.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z"/></svg>}
const socialLinks=[
  {href:'https://www.instagram.com/waslivo_agency/?utm_source=ig_web_button_share_sheet',label:'تابع وصليفو على إنستغرام',Icon:Instagram},
  {href:'https://www.facebook.com/profile.php?id=61595063485558',label:'تابع وصليفو على فيسبوك',Icon:Facebook},
  {href:'https://www.tiktok.com/@waslivo_agency',label:'تابع وصليفو على تيك توك',Icon:TiktokIcon},
];
function Footer(){return <footer className="footer"><div className="container footer-main"><div className="footer-brand"><Logo light/><div className="footer-social"><span>تابعنا على</span><div className="footer-social-links">{socialLinks.map(({href,label,Icon})=><a key={href} href={href} target="_blank" rel="noopener noreferrer" aria-label={label}><Icon size={20} aria-hidden="true"/></a>)}</div></div></div><div><h3>روابط سريعة</h3>{[['/','الرئيسية'],['/services','خدماتنا'],['/portfolio','أعمالنا'],['/packages','باقاتنا'],['/about','من نحن'],['/blog','مقالات'],['/contact','تواصل معنا']].map(([to,label])=><Link key={to} to={to}>{label}</Link>)}</div><div><h3>خدماتنا</h3>{services.slice(0,6).map(s=><Link key={s.id} to={`/services/${s.id}`}>{s.title}</Link>)}</div><div className="footer-contact"><h3>تواصل معنا</h3><p>نحن هنا للإجابة عن استفسارك ومناقشة مشروعك القادم.</p><WButton>ابدأ المحادثة عبر واتساب</WButton></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} وصليفو. جميع الحقوق محفوظة.</span><div><Link to="/privacy">سياسة الخصوصية</Link><Link to="/terms">الشروط والأحكام</Link></div></div></footer>}
function SectionTitle({eyebrow,title,description,light=false,align='center'}){return <div className={`section-title ${light?'section-title-light':''} ${align==='start'?'section-title-start':''}`}><span>{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>}
function Hero({variant='services',eyebrow,title,accent,description,primary='تواصل معنا عبر واتساب',secondary,secondaryTo='/portfolio',children}){const img={services:'visuals/hero-main.webp',packages:'visuals/hero-main.webp',about:'about-studio-v2.webp',contact:'visuals/contact-main.webp'}[variant];return <section className={`hero hero-${variant}`}><img className="hero-image" src={asset(img)} alt="" fetchPriority="high"/><div className="hero-gradient"/><div className="container hero-inner"><div className="hero-content"><span className="eyebrow">{eyebrow}</span><h1>{title}<em>{accent}</em></h1><p>{description}</p>{children}<div className="hero-actions"><WButton message={variant==='packages'?waText.packages:waText.general} kind={variant==='packages'?'green':'gold'}>{primary}</WButton>{secondary&&(secondaryTo.startsWith('tel:')?<a href={secondaryTo} className="button button-outline">{secondary}<ArrowLeft size={18}/></a>:<Link to={secondaryTo} className="button button-outline">{secondary}<ArrowLeft size={18}/></Link>)}</div></div></div>{variant==='about'&&<img className="hero-wall-logo" src={asset('waslivo-logo.webp')} alt="" aria-hidden="true"/>}</section>}
function BenefitStrip(){const items=[[Zap,'تواصل مباشر','عبر واتساب'],[MessageCircle,'نفهم فكرتك','ونناقش احتياجاتك'],[ShieldCheck,'عرض واضح','بعد تحديد نطاق العمل'],[Heart,'نعمل معك','من الفكرة حتى الإطلاق']];return <div className="benefit-strip"><div className="container benefit-inner">{items.map(([Icon,title,subtitle])=><div key={title} className="benefit"><Icon/><strong>{title}</strong><small>{subtitle}</small></div>)}</div></div>}
function ServiceCard({service:s,index,compact=false}){const Icon=icons[s.id];return <Link to={`/services/${s.id}`} className={`service-card ${compact?'service-card-compact':''} ${index<2?'service-card-core':''}`}><div className="service-image"><img src={asset(s.image)} loading="lazy" alt=""/><span className="service-icon"><Icon/></span></div><div className="service-copy"><h3>{s.title}</h3><p>{s.short}</p><span className="inline-link">اطلب الخدمة <ArrowLeft size={15}/></span></div></Link>}
function ServicesGrid({home=false}){return <section className={`section services-section ${home?'services-home':''}`} id="services"><div className="container"><SectionTitle eyebrow="خدماتنا" title={home?'حلول رقمية متكاملة لنمو أعمالك':'كل ما تحتاجه لبناء حضور رقمي احترافي'} description="من الفكرة إلى الإطلاق، نوفر لك ما تحتاجه لبناء حضور رقمي يعكس نشاطك باحتراف."/><div className={`service-grid ${home?'service-grid-seven':'service-grid-page'}`}>{services.map((s,i)=><ServiceCard key={s.id} service={s} index={i} compact={home}/>)}</div></div></section>}
function ProjectVisual({project:p,large=false,preview=false}){return <div className={`project-visual project-visual-photo ${large?'project-visual-large':''}`}>{large?<picture><img src={p.images.desktop} width="1050" height="1050" alt={`واجهة الحاسوب لموقع ${p.title}`} fetchPriority="high"/></picture>:<img src={preview&&p.previewImage?p.previewImage:p.images.desktop} alt={`تصوّر تصميم ${p.title}`} loading="lazy"/>}</div>}
function ShowcaseScreen({project,device}){return <img className="demo-screen-image" src={project.images[device]} width={device==='desktop'?1050:353} height="1050" alt={`واجهة ${device==='desktop'?'الحاسوب':'الجوال'} لموقع ${project.title}`} loading="lazy"/>}
function ProjectCard({project:p,compact=false,preview=false}){return <Link to={`/portfolio/${p.id}`} className={`project-card ${compact?'project-card-compact':''} ${preview?`project-card-preview project-card-preview-${p.id}`:''}`}><ProjectVisual project={p} preview={preview}/><div className="project-card-body"><span className="project-tag">{p.filter}</span><span className="project-concept">تصميم وتطوير موقع {p.title.replace(/^موقع\s+/, '')}</span><h3>{p.title}</h3><p>{p.summary}</p><span className="inline-link">عرض المشروع <ArrowLeft size={17}/></span></div></Link>}
function HomePortfolio(){return <section className="home-portfolio"><div className="container"><div className="home-portfolio-head"><div><span className="eyebrow">أعمالنا</span><h2>مشاريع نفخر بتصميمها</h2><p>نماذج تصوّرية في مجالات مختلفة تُظهر جودة التصميم ووضوح التجربة.</p></div><Link to="/portfolio" className="button button-gold">عرض المزيد من أعمالنا <ArrowLeft size={17}/></Link></div><div className="home-project-row">{projects.filter(p=>p.featured).map(p=><ProjectCard key={p.id} project={p} compact preview/>)}</div></div></section>}
const steps=[[MessageCircle,'فهم احتياجاتك','نستمع لأهدافك ونحدد متطلبات المشروع بدقة.'],[Palette,'التخطيط والتصميم','نرسم بنية واضحة ونصمم واجهة تعكس هويتك.'],[Code2,'التطوير والاختبار','نحوّل التصميم إلى موقع عملي ونختبره على الأجهزة.'],[TrendingUp,'الإطلاق والدعم','نجهّز الموقع للإطلاق ونتفق على الدعم المناسب.']];
function Process({pricing=false}){if(!pricing)return <ProcessSection/>;return <section className="section process-section" id="process"><div className="container"><SectionTitle eyebrow={pricing?'كيف نحدد السعر؟':'كيف نعمل'} title={pricing?'عملية بسيطة وواضحة لتسعير مشروعك':'رحلة واضحة من الفكرة إلى الإطلاق'} description={pricing?'نعتمد على فهم متطلباتك بدقة لنقدم لك عرضاً مناسباً يحقق أفضل قيمة لمشروعك.':'نتبع خطوات منظمة تمنح مشروعك تجربة سلسة ونتيجة واضحة.'}/><div className="steps">{steps.map(([Icon,title,copy],i)=><div className="step" key={title}><div className="step-top"><Icon/><span>{String(i+1).padStart(2,'0')}</span></div><h3>{pricing?['مناقشة المتطلبات','تحليل الاحتياجات','تقديم عرض مخصص','البدء والتنفيذ'][i]:title}</h3><p>{pricing?['نتعرف على أهدافك ومواصفات المشروع.','نحدد نطاق العمل والميزات المطلوبة.','نرسل لك عرض سعر تفصيلي مناسب.','نبدأ وفق جدول زمني متفق عليه.'][i]:copy}</p></div>)}</div></div></section>}
function FAQ({short=false,aside=false}){const qs=short?faqItems.slice(0,5):faqItems;return <section className={`section faq-section ${aside?'faq-with-aside':''}`} id="faq"><div className="container"><SectionTitle eyebrow="الأسئلة الشائعة" title="أجوبة سريعة لأهم استفساراتك" description={aside?'أجوبة واضحة قبل أن نبدأ الحديث عن مشروعك.':'إجابات عن الأسئلة التي تصلنا قبل بدء المشروع.'}/><div className="faq-layout"><div className="faq-items">{qs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div>{aside&&<div className="faq-picture"><img src={asset('visuals/faq-support.webp')} alt="مساحة عمل لتخطيط مشروع رقمي" loading="lazy"/><div><strong>لديك سؤال آخر؟</strong><WButton>اسألنا عبر واتساب</WButton></div></div>}</div></div></section>}
function CTA({title='لديك مشروع في ذهنك؟',copy='دعنا نحوله إلى تجربة رقمية احترافية تعكس هويتك وتحقق أهدافك.',compact=false}){return <section className={`cta ${compact?'cta-compact':''}`}><div className="container cta-content"><div><span className="eyebrow">لنصنع شيئاً مميزاً معاً</span><h2>{title}</h2><p>{copy}</p></div><WButton>تواصل معنا عبر واتساب <ArrowLeft size={17}/></WButton></div></section>}
function FAQAndCallout(){return <section className="section faq-callout" id="faq"><div className="container faq-callout-grid"><div><span className="eyebrow">الأسئلة الشائعة</span><h2>أجوبة سريعة لأهم استفساراتك</h2><div className="faq-items">{faqItems.slice(0,5).map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></div><div className="work-callout"><img src={asset('visuals/faq-support.webp')} alt="" loading="lazy"/><div><h3>لديك مشروع في ذهنك؟<br/>لنحوّله إلى واقع رقمي مميز</h3><p>تواصل معنا الآن وحدثنا عن فكرتك.</p><WButton>تواصل معنا عبر واتساب</WButton></div></div></div></section>}
function Home(){return <><HomeHero/><HomeTrust/><ServicesGrid home/><HomePortfolio/><Process/><FAQAndCallout/><CTA compact/></>}
function ServicesPage(){return <><Hero variant="services" eyebrow="خدماتنا" title="حلول رقمية متكاملة" accent="لنمو أعمالك" description="نقدم مجموعة متكاملة من الخدمات الرقمية المصممة لبناء حضور احترافي لعلامتك، من تصميم المواقع وتطويرها إلى التطبيقات والهوية البصرية." secondary="عرض أعمالنا" secondaryTo="/portfolio"/><ServicesGrid/><div className="container service-values">{[[Star,'تصاميم عصرية ومميزة','تجمع بين الإبداع وهوية علامتك'],[Zap,'حلول مخصصة لكل نشاط','نفهم احتياجك ونقترح الحل المناسب'],[HeartHandshake,'تواصل واضح ومستمر','نراجع معك القرارات في كل خطوة'],[ShieldCheck,'جودة واحترافية عالية','نراجع التفاصيل قبل تسليم المشروع']].map(([Icon,title,copy])=><div key={title}><Icon/><strong>{title}</strong><small>{copy}</small></div>)}</div><Process/><FAQAndCallout/><CTA/></>}
function ServiceDetail({id}){const s=services.find(x=>x.id===id);if(!s)return <NotFound/>;const Icon=icons[s.id];return <><Hero variant="services" eyebrow="خدماتنا" title={s.title} accent="بما يناسب أعمالك" description={s.detail} secondary="استكشف أعمالنا" secondaryTo="/portfolio"/><section className="section container service-detail"><div><span className="eyebrow">ما الذي نقدمه؟</span><h2>حلّ عملي يبدأ بفهم مشروعك</h2><p>{s.detail}</p><div className="detail-points">{s.points.map(x=><div key={x}><Check/>{x}</div>)}</div><WButton message={`مرحباً وصليفو، أود الاستفسار عن ${s.title}.`}>ناقش مشروعك معنا</WButton></div><div className="service-detail-image"><img src={asset(s.image)} alt={'صورة تعبر عن خدمة '+s.title} loading="lazy"/><span><Icon/>{s.title}</span></div></section><Process/><CTA title="جاهز للبدء؟"/></>}
function PortfolioPage(){const [filter,setFilter]=useState('الكل');const shown=filter==='الكل'?projects:projects.filter(p=>p.filter===filter);return <><section className="portfolio-hero"><img src={asset('visuals/hero-main.webp')} alt=""/><div className="portfolio-hero-gradient"/><div className="container portfolio-hero-inner"><div><span className="eyebrow">أبرز نماذجنا</span><h1>من الفكرة إلى تجربة رقمية<br/><em>تصنع فرقاً حقيقياً</em></h1><p>نطوّر تصوّرات لمواقع تجمع بين الهوية الواضحة وتجربة الاستخدام المدروسة.</p><div className="featured-info"><span>موقع عقاري</span><h2>منصة لاستكشاف العقارات</h2><p>تجربة منظمة تعرض الوحدات وتفاصيلها وتيسّر طلب المعاينة.</p><Link to="/portfolio/property" className="button button-gold">عرض تفاصيل المشروع <ArrowUpLeft size={17}/></Link></div></div></div></section><section className="section portfolio-page"><div className="container"><SectionTitle eyebrow="أعمالنا" title="مجموعة من التصاميم التي نفخر بها" description="استكشف نماذج أصلية لواجهات صممناها لتوضيح الإمكانات في مجالات مختلفة."/><div className="portfolio-filters" role="group" aria-label="تصفية النماذج">{filters.map(f=><button type="button" key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="portfolio-grid">{shown.map((p,i)=><ProjectCard key={p.id} project={p} preview/>)}</div><div className="portfolio-bottom"><div className="portfolio-inquiry"><img src={asset('visuals/about-method.webp')} alt="مساحة عمل لتصميم موقع رقمي" loading="lazy"/><div><h2>هل لديك فكرة مشروع؟</h2><p>نحوّل الأفكار إلى تجربة رقمية مناسبة لنشاطك وأهدافك.</p><WButton message={waText.portfolio}>تواصل معنا لبدء مشروعك</WButton></div></div></div></div></section><CTA compact/></>}
function ProjectDetail({id}){
 const p=projects.find(x=>x.id===id);
 if(!p)return <NotFound/>;
 return <>
  <section className="project-detail-hero"><div className="container">
   <div className="breadcrumbs"><Link to="/portfolio">أعمالنا</Link><ArrowLeft size={14}/><span>{p.title}</span></div>
   <div className="project-detail-heading"><div><span className="eyebrow">{p.filter} · تصوّر تصميمي</span><h1>{p.title}</h1><p>{p.summary}</p></div><WButton message={`مرحباً وصليفو، أعجبني نموذج ${p.title} وأود مناقشة مشروع مشابه.`}>أريد مشروعاً مشابهاً</WButton></div>
   <ProjectVisual project={p} large/>
  </div></section>
  <section className="section project-narrative"><div className="container narrative-grid"><div><span className="eyebrow">هدف المشروع</span><h2>موقع يسهل اتخاذ القرار</h2><p>{p.goal}</p></div><div><span className="eyebrow">اتجاه التصميم</span><h2>هوية واضحة وتجربة سهلة</h2><p>{p.solution}</p></div></div></section>
  <section className="section project-screens"><div className="container"><SectionTitle eyebrow="الشاشات الرئيسية" title="تفاصيل التصميم عبر الأجهزة" description="لقطات من الموقع كما يظهر على الحاسوب والجوال."/><div className="screen-grid demo-screen-grid"><div><div className="demo-preview-shell demo-preview-desktop"><div className="demo-preview-bar"><span className="demo-preview-dots"><i/><i/><i/></span><span>الحاسوب</span></div><ShowcaseScreen project={p} device="desktop"/></div><strong>واجهة الحاسوب</strong></div><div className="mobile-screen-preview"><div className="demo-preview-shell demo-preview-mobile"><ShowcaseScreen project={p} device="mobile"/></div><strong>واجهة الجوال</strong></div></div></div></section>
  <section className="section project-features"><div className="container"><SectionTitle eyebrow="ما يتضمنه النموذج" title="عناصر عملية في كل شاشة"/><div className="feature-grid">{p.features.map((f,i)=><div key={f}><span>{String(i+1).padStart(2,'0')}</span><Check/><h3>{f}</h3></div>)}</div></div></section>
  <section className="section container"><div className="related-head"><SectionTitle eyebrow="نماذج أخرى" title="استكشف المزيد" align="start"/><Link to="/portfolio" className="button button-outline">جميع النماذج <ArrowLeft size={17}/></Link></div><div className="portfolio-grid">{projects.filter(x=>x.id!==id).slice(0,3).map(x=><ProjectCard key={x.id} project={x}/>)}</div></section><CTA/>
 </>;
}
function AboutPage(){const values=[[Diamond,'الجودة في التفاصيل','نهتم بما يراه الزائر وما يساعده على فهم علامتك.'],[HeartHandshake,'تواصل واضح','نناقش كل قرار مهم ونعمل وفق نطاق متفق عليه.'],[Lightbulb,'حلول مخصصة','نختار ما يخدم احتياج المشروع بدل إضافة وظائف بلا هدف.'],[Heart,'تجربة إنسانية','نجعل استخدام الموقع مريحاً وواضحاً على كل شاشة.']];return <><Hero variant="about" eyebrow="من نحن" title="شريكك الإبداعي" accent="لبناء حضور رقمي مؤثر" description="وصليفو استوديو متخصص في تصميم وتطوير المواقع الإلكترونية والتطبيقات والهوية البصرية، يحوّل الأفكار إلى تجارب تساعد الأعمال على النمو والتواصل باحتراف." primary="تواصل معنا لبدء مشروعك"/><section className="section container about-story"><div><span className="eyebrow">قصتنا</span><h2>من فكرة إلى أثر رقمي حقيقي</h2><p>وُجدت وصليفو لتجعل الحضور الرقمي أوضح وأكثر تعبيراً عن كل مشروع. نبدأ بفهم الفكرة والجمهور، ثم نصمم تجربة متماسكة تجمع بين الجمال وسهولة الاستخدام.</p><p>نجمع التصميم والتطوير والهوية في مسار واحد، مع اهتمام بالمحتوى والتفاصيل التي يحتاجها العميل قبل أن يتواصل معك.</p></div><div className="about-story-image"><img src={asset('visuals/about-story.webp')} alt="مساحة عمل لتصميم موقع إلكتروني" loading="lazy"/><span><Lightbulb/> نؤمن بأن العلامة التجارية تستحق حضوراً رقمياً يليق بها.</span></div></section><section className="section values-section"><div className="container"><SectionTitle eyebrow="قيمنا" title="المبادئ التي تقود كل ما نعمل عليه" description="نضع علاقتنا مع عملائنا وتجربة المستخدم في قلب كل قرار."/><div className="value-grid">{values.map(([Icon,title,copy])=><div key={title}><Icon/><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section><section className="section container method-section"><div className="method-image"><img src={asset('visuals/about-method.webp')} alt="مساحة عمل تعرض عملية تصميم موقع إلكتروني" loading="lazy"/></div><div><span className="eyebrow">نهجنا</span><h2>كيف نبني حضوراً رقمياً متكاملاً؟</h2><p>نجمع بين فهم أهداف الأعمال، وبنية محتوى واضحة، وتصميم بصري متناسق، وتطوير عملي. بهذه الطريقة يصبح الموقع جزءاً مفيداً من رحلة العميل، وليس مجرد صفحة جميلة.</p><Link to="/services" className="button button-outline">اكتشف خدماتنا <ArrowLeft size={17}/></Link></div></section><Process/><CTA title="مستعد لبناء حضورك الرقمي؟"/></>}
const packages=[
  {name:'الباقة الأساسية',lead:'بداية احترافية لمشروعك',icon:PenTool,image:'visuals/package-basic.webp',items:['تصميم موقع احترافي واضح','صفحات أساسية وتعريفية','تجربة متجاوبة على الأجهزة','نموذج تواصل وربط واتساب','تهيئة أساسية لمحركات البحث']},
  {name:'الباقة المتقدمة',lead:'أعمال متنامية تبحث عن المزيد',icon:TrendingUp,image:'visuals/package-advanced.webp',items:['تصميم بهوية خاصة','صفحات ومحتوى أكثر تنظيماً','وظائف إضافية حسب الاحتياج','إعدادات بحث أوسع','تكاملات متفق عليها'],balanced:true},
  {name:'الباقة المخصصة',lead:'حلول متكاملة لمشاريع أكبر',icon:Diamond,image:'visuals/package-custom.webp',items:['تصميم وتطوير مخصصان بالكامل','ميزات متقدمة حسب مشروعك','متجر أو نظام أو بوابة خاصة','تكامل مع خدمات خارجية','دعم وتطوير حسب الاتفاق'],dark:true}
];
function PackageCard({item:p}){const Icon=p.icon;return <div className={`package-card ${p.dark?'package-card-dark':''}`}>{p.balanced&&<span className="package-ribbon">خيار متوازن</span>}<div className="package-title"><Icon/><div><h3>{p.name}</h3><p>{p.lead}</p></div></div><img src={asset(p.image)} alt="" loading="lazy"/><ul>{p.items.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><WButton message={`مرحباً وصليفو، أود مناقشة ${p.name} لمشروعي.`} kind={p.dark?'outline':'gold'}>ناقش مشروعك عبر واتساب</WButton></div>}
function PackagesPage(){return <><Hero variant="packages" eyebrow="باقاتنا" title="باقات مرنة تناسب" accent="احتياجات مشروعك" description="كل مشروع له متطلبات مختلفة؛ لذلك نقدم نطاقات مرنة نصممها بناءً على أهدافك، ثم نحدد التفاصيل والسعر المناسب." primary="ناقش مشروعك عبر واتساب" secondary="أرسل تفاصيل مشروعك" secondaryTo="/contact"><div className="price-box"><Wallet/><div>تبدأ الباقات من <strong>799 ريال</strong><small>السعر النهائي يتم تحديده بعد مناقشة تفاصيل المشروع والمتطلبات.</small></div></div></Hero><section className="section packages-section"><div className="container"><SectionTitle eyebrow="اختر ما يناسبك" title="باقاتنا المصممة لنمو أعمالك" description="نطاقات رئيسية تغطي احتياجات مختلفة، مع مرونة في التخصيص والإضافة."/><div className="package-grid">{packages.map(p=><PackageCard item={p} key={p.name}/>)}</div></div></section><Process pricing/><section className="section package-extras"><div className="container extras-layout"><div><span className="eyebrow">إضافات وخدمات اختيارية</span><h2>يمكن إضافة خدمات ومميزات إضافية</h2><p>نختار ما يحتاجه مشروعك ونحدده بوضوح في العرض.</p><div className="extra-list">{['متجر إلكتروني','حجز مواعيد','ربط مع أنظمة خارجية','محتوى احترافي','هوية بصرية','دعم وصيانة'].map(x=><span key={x}><Check size={15}/>{x}</span>)}</div></div><div className="extras-callout"><h3>مستعد لبدء مشروعك؟</h3><p>تواصل معنا عبر واتساب لمناقشة المتطلبات والحصول على عرض مخصص.</p><WButton kind="green" message={waText.packages}>تواصل معنا الآن عبر واتساب</WButton></div></div></section><FAQ/><CTA compact/></>}
function ContactForm(){const [form,setForm]=useState({name:'',email:'',phone:'',type:'موقع إلكتروني',budget:'',brief:''});const [error,setError]=useState('');const set=e=>setForm({...form,[e.target.name]:e.target.value});const send=e=>{e.preventDefault();if(!form.name.trim()||!form.email.trim()||!form.brief.trim()){setError('يرجى إدخال الاسم والبريد الإلكتروني وتفاصيل المشروع.');return}setError('');const message=`مرحباً وصليفو، أود مناقشة مشروع جديد.\nالاسم: ${form.name}\nالبريد الإلكتروني: ${form.email}\nالهاتف: ${form.phone||'غير مذكور'}\nنوع المشروع: ${form.type}\nالميزانية: ${form.budget||'لم تُحدّد بعد'}\nتفاصيل المشروع: ${form.brief}`;window.open(whatsapp(message),'_blank','noopener,noreferrer')};return <form className="contact-form" onSubmit={send}><span className="eyebrow">تواصل معنا</span><h2>أرسل لنا تفاصيل مشروعك</h2><p>أكمل النموذج لفتح رسالة واتساب جاهزة تراجعها وترسلها بنفسك.</p><div className="field-row"><label>الاسم الكامل <b>*</b><input name="name" value={form.name} onChange={set} autoComplete="name" required placeholder="اسمك الكامل"/></label><label>البريد الإلكتروني <b>*</b><input name="email" type="email" dir="ltr" value={form.email} onChange={set} autoComplete="email" required placeholder="name@example.com"/></label></div><div className="field-row"><label>رقم الهاتف<input name="phone" type="tel" dir="ltr" value={form.phone} onChange={set} autoComplete="tel" placeholder="رقم للتواصل"/></label><label>نوع المشروع<select name="type" value={form.type} onChange={set}>{['موقع إلكتروني','متجر إلكتروني','تطبيق جوال','هوية بصرية','شعار','منشورات سوشيال ميديا','تطوير مخصص','أخرى'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>الميزانية التقريبية<input name="budget" value={form.budget} onChange={set} placeholder="إن كانت محددة"/></label><label>تفاصيل المشروع <b>*</b><textarea name="brief" value={form.brief} onChange={set} required rows="5" placeholder="حدثنا عن فكرتك وأهدافك باختصار..."/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-gold" type="submit"><Send size={17}/> متابعة عبر واتساب</button></form>}
function ContactPage(){return <><Hero variant="contact" eyebrow="تواصل معنا" title="نحن هنا لخدمة فكرتك" accent="تواصل معنا بكل سهولة" description="سواء كان لديك استفسار أو فكرة مشروع جديدة، فريقنا جاهز للرد عليك ومناقشة الخطوة المناسبة بكل احترافية." primary="راسلنا عبر واتساب" secondary="اتصال هاتفي" secondaryTo={`tel:+${whatsappNumber}`}/><BenefitStrip contact/><section className="section contact-section"><div className="container contact-layout"><ContactForm/><div className="contact-side" id="contact-methods"><div className="whatsapp-card"><span>الوسيلة الأسرع للتواصل</span><h2>تواصل معنا عبر واتساب</h2><p>ابدأ محادثة مباشرة وأخبرنا عن فكرتك.</p><WButton kind="green">راسلنا عبر واتساب</WButton></div><div className="other-methods"><h3>طرق أخرى للتواصل</h3><a href={`tel:+${whatsappNumber}`}><Phone/> اتصال هاتفي <small>+212 633 485 489</small></a><p>يمكنك أيضاً استخدام النموذج لإعداد رسالة واتساب تتضمن تفاصيل مشروعك.</p></div></div></div></section><FAQ aside/><CTA title="لنحوّل فكرتك إلى حضور رقمي احترافي"/></>}
function BlogPage(){return <><section className="editorial-hero"><div className="container"><span className="eyebrow">مقالات وأفكار</span><h1>معرفة تساعدك على بناء موقع أفضل</h1><p>أفكار عملية عن التصميم والمحتوى وتجربة المستخدم والهوية الرقمية.</p></div></section><section className="section container"><SectionTitle eyebrow="من مدونتنا" title="اقرأ قبل أن تبدأ"/><div className="article-grid">{articles.map((a,i)=><Link to={`/blog/${a.id}`} className="article-card" key={a.id}><div className="article-image"><img src={asset(['visuals/blog-brief.webp','visuals/blog-brand.webp','visuals/blog-mobile.webp'][i])} alt="" loading="lazy"/></div><div><small>{a.category} · فريق وصليفو</small><h2>{a.title}</h2><p>{a.intro}</p><span className="inline-link">اقرأ المقال <ArrowLeft size={16}/></span></div></Link>)}</div></section><CTA/></>}
function ArticlePage({id}){const a=articles.find(x=>x.id===id);if(!a)return <NotFound/>;return <><section className={`editorial-hero editorial-hero-${id}`}><div className="container"><div className="breadcrumbs"><Link to="/blog">مقالات وأفكار</Link><ArrowLeft size={14}/><span>{a.category}</span></div><span className="eyebrow">{a.category} · فريق وصليفو</span><h1>{a.title}</h1><p>{a.intro}</p></div></section><div className="section container article-layout"><article>{a.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<WButton message={`مرحباً وصليفو، قرأت مقال «${a.title}» وأود مناقشة موقعي.`}>ناقش مشروعك معنا</WButton></article><aside><h3>مقالات أخرى</h3>{articles.filter(x=>x.id!==id).map(x=><Link key={x.id} to={`/blog/${x.id}`}>{x.title}<ArrowLeft size={15}/></Link>)}</aside></div><CTA compact/></>}
function LegalPage({type}){const privacy=type==='privacy';return <section className="section legal-page container"><span className="eyebrow">وصليفو</span><h1>{privacy?'سياسة الخصوصية':'الشروط والأحكام'}</h1>{privacy?<><p>عند استخدام نموذج التواصل، يفتح الموقع رسالة واتساب بالمعلومات التي كتبتها. لا تُرسل الرسالة إلا عندما تختار إرسالها داخل واتساب.</p><p>عند الانتقال إلى واتساب، تخضع المحادثة لسياسات الخدمة التي تستخدمها. يمكنك التواصل معنا عبر واتساب للاستفسار عن بياناتك في المحادثات.</p></>:<><p>المحتوى المعروض على الموقع للتعريف بخدمات وصليفو. نماذج الأعمال تصوّرات تصميمية توضيحية حتى يُشار إلى غير ذلك بوضوح.</p><p>يُحدد نطاق كل مشروع ومخرجاته وجدوله وسعره النهائي في عرض منفصل بعد مناقشة المتطلبات.</p></>}<Link to="/contact" className="button button-outline">تواصل معنا <ArrowLeft size={17}/></Link></section>}
function NotFound(){return <section className="not-found"><div className="container"><span>404</span><h1>الصفحة غير موجودة</h1><p>قد يكون الرابط غير صحيح أو تغير عنوان الصفحة.</p><Link to="/" className="button button-gold">العودة للرئيسية <ArrowLeft size={17}/></Link></div></section>}
function Page({path}){const bits=path.split('/').filter(Boolean);if(path==='/')return <Home/>;if(bits[0]==='services')return bits[1]?<ServiceDetail id={bits[1]}/>:<ServicesPage/>;if(bits[0]==='portfolio'||bits[0]==='works'||bits[0]==='work')return bits[1]?<ProjectDetail id={bits[1]}/>:<PortfolioPage/>;if(path==='/about')return <AboutPage/>;if(path==='/packages')return <PackagesPage/>;if(path==='/contact')return <ContactPage/>;if(bits[0]==='blog')return bits[1]?<ArticlePage id={bits[1]}/>:<BlogPage/>;if(path==='/privacy'||path==='/terms')return <LegalPage type={bits[0]}/>;return <NotFound/>}
const route=()=>typeof window==='undefined'?'/':decodeURIComponent(window.location.pathname).replace(/\/$/,'')||'/';
function updateMetadata(path){
  const seo=getSeo(path);
  document.documentElement.lang=seo?.lang||(path.startsWith('/en')?'en':'ar');
  document.documentElement.dir=seo?.lang==='en'?'ltr':'rtl';
  document.title=seo?.title||(path.startsWith('/en')?'Page not found | WASLIVO':'الصفحة غير موجودة | وصليفو');
  const meta=(selector,attributes)=>{
    let element=document.head.querySelector(selector);
    if(!element){element=document.createElement('meta');document.head.appendChild(element)}
    Object.entries(attributes).forEach(([name,value])=>element.setAttribute(name,value));
  };
  meta('meta[name="robots"]',{name:'robots',content:seo?'index,follow,max-image-preview:large':'noindex,follow'});
  if(!seo){
    document.querySelector('link[rel="canonical"]')?.remove();
    document.querySelectorAll('link[rel="alternate"][hreflang]')?.forEach(link=>link.remove());
    document.getElementById('waslivo-structured-data')?.remove();
    return;
  }
  meta('meta[name="description"]',{name:'description',content:seo.description});
  for(const [property,content] of Object.entries({'og:type':seo.kind==='article'?'article':'website','og:title':seo.title,'og:description':seo.description,'og:url':seo.url,'og:image':seo.image,'og:site_name':'WASLIVO'}))meta(`meta[property="${property}"]`,{property,content});
  for(const [name,content] of Object.entries({'twitter:card':'summary_large_image','twitter:title':seo.title,'twitter:description':seo.description,'twitter:image':seo.image}))meta(`meta[name="${name}"]`,{name,content});
  let canonical=document.querySelector('link[rel="canonical"]');
  if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}
  canonical.href=seo.url;
  for(const [lang,href] of [['ar',seo.arUrl],['en',seo.enUrl]]){
    let alternate=document.querySelector(`link[rel="alternate"][hreflang="${lang}"]`);
    if(!alternate){alternate=document.createElement('link');alternate.rel='alternate';alternate.hreflang=lang;document.head.appendChild(alternate)}
    alternate.href=href;
  }
  let schema=document.getElementById('waslivo-structured-data');
  if(!schema){schema=document.createElement('script');schema.id='waslivo-structured-data';schema.type='application/ld+json';document.head.appendChild(schema)}
  schema.textContent=JSON.stringify(getStructuredData(seo));
}

export default function App({initialPath}){const [path,setPath]=useState(()=>initialPath||route());useEffect(()=>{if(location.hash.startsWith('#/')){const old=location.hash.slice(1);history.replaceState({},'',old);setPath(route())}const onPop=()=>setPath(route());addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop)},[]);useEffect(()=>{updateMetadata(path)},[path]);useLayoutEffect(()=>{
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const sections=document.querySelectorAll('main .section-title,main .home-portfolio-head,main .benefit-inner,main .cta-content,main .portfolio-hero-inner,main .editorial-hero .container,main .narrative-grid,main .contact-layout,main .about-story,main .method-section,main .faq-layout,main .faq-callout-grid,main .project-detail-heading,.footer-main');
  const cards=document.querySelectorAll('main .service-card,main .project-card,main .package-card,main .article-card,main .step');
  const targets=[...sections,...cards];
  targets.forEach((node,index)=>{node.classList.add('reveal-target');if(node.matches('.service-card,.project-card,.package-card,.article-card,.step'))node.style.setProperty('--reveal-delay',`${(index%5)*70}ms`)});
  document.documentElement.classList.add('motion-ready');
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:0.12,rootMargin:'0px 0px -5% 0px'});
  targets.forEach(node=>observer.observe(node));
  return()=>{observer.disconnect();targets.forEach(node=>{node.classList.remove('reveal-target','is-visible');node.style.removeProperty('--reveal-delay')})};
 },[path]);return path==='/en'||path.startsWith('/en/')?<EnglishSite path={path}/>:<><Header path={path}/><main><Page path={path}/></main><Footer/><a className="floating-whatsapp" href={whatsapp(waText.general)} target="_blank" rel="noopener noreferrer" aria-label="تواصل معنا عبر واتساب"><WhatsappIcon/></a></>}
